package render

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dreasy-dev/repomap/internal/model"
)

// Write renders the full index to outDir as organized Markdown + JSON files.
func Write(outDir string, idx *model.Index) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	writers := map[string]func(*model.Index) string{
		"MANIFEST.md":  manifest,
		"TREE.md":      tree,
		"SYMBOLS.md":   symbols,
		"IMPORTS.md":   imports,
		"ENDPOINTS.md": endpoints,
		"CALLGRAPH.md": callgraph,
	}
	for name, fn := range writers {
		if err := os.WriteFile(filepath.Join(outDir, name), []byte(fn(idx)), 0o644); err != nil {
			return err
		}
	}
	if err := writeJSON(filepath.Join(outDir, "index.json"), idx); err != nil {
		return err
	}
	return writeJSON(filepath.Join(outDir, ".meta.json"), meta(idx))
}

func writeJSON(path string, v any) error {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

func meta(idx *model.Index) map[string]any {
	files := map[string]string{}
	for _, f := range idx.Files {
		files[f.Path] = f.Hash
	}
	return map[string]any{
		"generated_at": idx.GeneratedAt,
		"git_commit":   idx.GitCommit,
		"hash":         idx.Hash,
		"counts": map[string]int{
			"files": len(idx.Files), "symbols": len(idx.Symbols),
			"imports": len(idx.Imports), "endpoints": len(idx.Endpoints),
		},
		"files": files,
	}
}

func manifest(idx *model.Index) string {
	var b strings.Builder
	b.WriteString("# Codebase Index — MANIFEST\n\n")
	b.WriteString("> Generated by `repomap`. Agents: read this first. Run `repomap check` to verify freshness, `repomap build` to refresh.\n\n")
	fmt.Fprintf(&b, "- Generated: `%s`\n", idx.GeneratedAt.Format("2006-01-02 15:04:05"))
	if idx.GitCommit != "" {
		fmt.Fprintf(&b, "- Git commit: `%s`\n", idx.GitCommit)
	}
	fmt.Fprintf(&b, "- Files indexed: **%d** · Symbols: **%d** · Endpoints: **%d** · Call edges: **%d**\n\n", len(idx.Files), len(idx.Symbols), len(idx.Endpoints), len(idx.CallGraph))

	b.WriteString("## How to run / build / test\n\n")
	p := idx.Project
	for _, m := range p.Modules {
		fmt.Fprintf(&b, "- Go module `%s` in `%s` (go %s)\n", m.Path, dirLabel(m.Dir), m.GoVersion)
	}
	for _, app := range p.NodeApps {
		fmt.Fprintf(&b, "- npm app in `%s`:\n", dirLabel(app.Dir))
		for _, k := range sortedKeys(app.Scripts) {
			fmt.Fprintf(&b, "  - `%s` → `%s`\n", k, app.Scripts[k])
		}
	}
	if len(p.MakeTargets) > 0 {
		fmt.Fprintf(&b, "- Make targets: %s\n", codeList(p.MakeTargets))
	}
	if p.HasDocker {
		b.WriteString("- Dockerfile present\n")
	}
	if len(p.EntryPoints) > 0 {
		fmt.Fprintf(&b, "- Entry points: %s\n", codeList(p.EntryPoints))
	}
	b.WriteString("\n## Map\n\n")
	b.WriteString("- `TREE.md` — annotated directory tree\n")
	b.WriteString("- `SYMBOLS.md` — every function/type/export → `file:line`\n")
	b.WriteString("- `IMPORTS.md` — internal dependency graph\n")
	b.WriteString("- `ENDPOINTS.md` — HTTP routes (Go + Next.js)\n")
	b.WriteString("- `CALLGRAPH.md` — Go call graph (caller \u2194 callee)\n")
	b.WriteString("- `index.json` — full machine-readable index\n")
	return b.String()
}

func tree(idx *model.Index) string {
	var b strings.Builder
	b.WriteString("# Directory Tree\n\n```\n")
	paths := make([]string, len(idx.Files))
	for i, f := range idx.Files {
		paths[i] = f.Path
	}
	sort.Strings(paths)
	seen := map[string]bool{}
	for _, p := range paths {
		segs := strings.Split(p, "/")
		for i := range segs {
			prefix := strings.Join(segs[:i+1], "/")
			if seen[prefix] {
				continue
			}
			seen[prefix] = true
			indent := strings.Repeat("  ", i)
			name := segs[i]
			if i < len(segs)-1 {
				name += "/"
			}
			fmt.Fprintf(&b, "%s%s\n", indent, name)
		}
	}
	b.WriteString("```\n")
	return b.String()
}

func symbols(idx *model.Index) string {
	byFile := map[string][]model.Symbol{}
	for _, s := range idx.Symbols {
		byFile[s.File] = append(byFile[s.File], s)
	}
	var b strings.Builder
	b.WriteString("# Symbols\n\n")
	b.WriteString("Exact locations so agents never grep for a definition.\n\n")
	for _, file := range sortedKeys(byFile) {
		syms := byFile[file]
		sort.Slice(syms, func(i, j int) bool { return syms[i].Line < syms[j].Line })
		fmt.Fprintf(&b, "### `%s`\n\n", file)
		for _, s := range syms {
			loc := fmt.Sprintf("%s:%d", s.File, s.Line)
			label := s.Name
			if s.Receiver != "" {
				label = "(" + s.Receiver + ") " + s.Name
			}
			fmt.Fprintf(&b, "- `%s` **%s** — `%s`", label, s.Kind, loc)
			if s.Signature != "" {
				fmt.Fprintf(&b, " — `%s`", oneLine(s.Signature))
			}
			if s.Doc != "" {
				fmt.Fprintf(&b, " — %s", s.Doc)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	return b.String()
}

func imports(idx *model.Index) string {
	var b strings.Builder
	b.WriteString("# Import Graph\n\n")
	b.WriteString("Who depends on what. Local imports first.\n\n")
	prefixes := idx.Project.ModulePaths
	isLocal := func(im string) bool {
		if strings.HasPrefix(im, ".") || strings.HasPrefix(im, "@/") || strings.HasPrefix(im, "~/") {
			return true
		}
		for _, mp := range prefixes {
			if im == mp || strings.HasPrefix(im, mp+"/") {
				return true
			}
		}
		return false
	}
	for _, e := range idx.Imports {
		var local, ext []string
		for _, im := range e.Imports {
			if isLocal(im) {
				local = append(local, im)
			} else {
				ext = append(ext, im)
			}
		}
		if len(local) == 0 && len(ext) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### `%s`\n", e.File)
		if len(local) > 0 {
			fmt.Fprintf(&b, "- local: %s\n", codeList(local))
		}
		if len(ext) > 0 {
			fmt.Fprintf(&b, "- external: %s\n", codeList(ext))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func endpoints(idx *model.Index) string {
	var b strings.Builder
	b.WriteString("# HTTP Endpoints\n\n")
	if len(idx.Endpoints) == 0 {
		b.WriteString("_None detected._\n")
		return b.String()
	}
	eps := append([]model.Endpoint(nil), idx.Endpoints...)
	sort.Slice(eps, func(i, j int) bool {
		if eps[i].Path != eps[j].Path {
			return eps[i].Path < eps[j].Path
		}
		return eps[i].Method < eps[j].Method
	})
	b.WriteString("| Method | Path | File | Framework |\n|---|---|---|---|\n")
	for _, e := range eps {
		loc := e.File
		if e.Line > 0 {
			loc = fmt.Sprintf("%s:%d", e.File, e.Line)
		}
		fmt.Fprintf(&b, "| %s | `%s` | `%s` | %s |\n", e.Method, e.Path, loc, e.Framework)
	}
	return b.String()
}

func callgraph(idx *model.Index) string {
	var b strings.Builder
	b.WriteString("# Call Graph (Go)\n\n")
	b.WriteString("Who calls what, resolved within the module. Functions only; methods and external packages are skipped.\n\n")
	if len(idx.CallGraph) == 0 {
		b.WriteString("_No internal calls resolved._\n")
		return b.String()
	}

	b.WriteString("## Forward (caller \u2192 callees)\n\n")
	var curKey string
	for _, e := range idx.CallGraph {
		key := fmt.Sprintf("%s|%d", e.FromFile, e.FromLine)
		if key != curKey {
			curKey = key
			fmt.Fprintf(&b, "\n### `%s` — `%s:%d`\n", e.From, e.FromFile, e.FromLine)
		}
		fmt.Fprintf(&b, "- \u2192 `%s` — `%s:%d`\n", e.To, e.ToFile, e.ToLine)
	}

	b.WriteString("\n## Reverse (callee \u2190 callers)\n\n")
	type callerRef struct{ from, file string; line int }
	rev := map[string][]callerRef{}
	order := []string{}
	for _, e := range idx.CallGraph {
		k := fmt.Sprintf("%s\x00%s:%d", e.To, e.ToFile, e.ToLine)
		if _, ok := rev[k]; !ok {
			order = append(order, k)
		}
		rev[k] = append(rev[k], callerRef{e.From, e.FromFile, e.FromLine})
	}
	sort.Strings(order)
	for _, k := range order {
		parts := strings.SplitN(k, "\x00", 2)
		fmt.Fprintf(&b, "\n### `%s` — `%s`\n", parts[0], parts[1])
		for _, c := range rev[k] {
			fmt.Fprintf(&b, "- \u2190 `%s` — `%s:%d`\n", c.from, c.file, c.line)
		}
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func codeList(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func dirLabel(dir string) string {
	if dir == "." || dir == "" {
		return "(root)"
	}
	return dir
}
